#!/bin/sh

riscv64-unknown-elf-as -o bin/compress.o src/compress.S || exit 1
riscv64-unknown-elf-objcopy -O binary bin/compress.o bin/compress.bin || exit 1

qemu-system-riscv64 \
        -machine virt \
        -nographic \
        -bios none \
        -smp 4 \
        -device loader,file=./bin/node.bin,addr=0x80000000
